### ISSUE TITLE
Affichage mal formaté du taux de contribution patronale

### ISSUE THREAD

**Issue by gouchere** [gouchere/Lymytz_Erp#57]
Sur la page des Paramétrage statistiques, / Récap CF. L'affichage du tax de contribution est à 2 au lieu de 1.5. Pourtant dan la base de données  (table yvs_stat_grh_taux_contribution) la valeur enregitré est bien 1.5
Note: Voir le converter sur la page

![image](https://github.com/gouchere/Lymytz_Erp/assets/45066513/d95f3d67-0ffd-4ccd-b69e-7107ce5524db)

**Comment by dowesw** [comment]
Vérifie si c'est sur cette page que le formatage n'était pas correct car,
La valeur ne change pas même sans converter

![image](https://github.com/gouchere/Lymytz_Erp/assets/6861482/bd50456c-575d-4ea6-8bc1-568504b92fde)
